# Generated by Django 4.1.3 on 2022-11-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role_companies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=100)),
                ("role_id", models.IntegerField()),
                ("company_name", models.CharField(max_length=100)),
                ("link", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Role_skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=100)),
                ("role_id", models.IntegerField()),
                ("skill", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Roles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=100)),
                ("role_id", models.IntegerField()),
                ("q1_2021_nr_jobs", models.IntegerField()),
                ("q2_2021_nr_jobs", models.IntegerField()),
                ("q3_2021_nr_jobs", models.IntegerField()),
                ("q4_2021_nr_jobs", models.IntegerField()),
                ("q1_2022_nr_jobs", models.IntegerField()),
                ("q2_2022_nr_jobs", models.IntegerField()),
                ("q3_2022_nr_jobs", models.IntegerField()),
                ("q4_2022_nr_jobs", models.IntegerField()),
                ("salary", models.IntegerField()),
            ],
        ),
    ]
