# Generated by Django 4.1.3 on 2022-11-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oxhack", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill", models.CharField(max_length=100)),
            ],
        ),
    ]
