# Generated by Django 4.1.3 on 2022-11-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oxhack", "0002_skills"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roles",
            name="q1_2021_nr_jobs",
        ),
        migrations.RemoveField(
            model_name="roles",
            name="q1_2022_nr_jobs",
        ),
        migrations.RemoveField(
            model_name="roles",
            name="q2_2021_nr_jobs",
        ),
        migrations.RemoveField(
            model_name="roles",
            name="q2_2022_nr_jobs",
        ),
        migrations.RemoveField(
            model_name="roles",
            name="q3_2021_nr_jobs",
        ),
        migrations.RemoveField(
            model_name="roles",
            name="q3_2022_nr_jobs",
        ),
        migrations.RemoveField(
            model_name="roles",
            name="q4_2021_nr_jobs",
        ),
        migrations.RemoveField(
            model_name="roles",
            name="q4_2022_nr_jobs",
        ),
        migrations.AddField(
            model_name="roles",
            name="category",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="roles",
            name="jobs_2019",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="roles",
            name="jobs_2020",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="roles",
            name="jobs_2021",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="roles",
            name="jobs_2022",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="roles",
            name="jobs_2023",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="roles",
            name="jobs_2024",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="roles",
            name="jobs_2025",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="roles",
            name="jobs_2026",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="roles",
            name="jobs_2027",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="roles",
            name="jobs_2028",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="roles",
            name="jobs_2029",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="roles",
            name="jobs_2030",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="role_companies",
            name="link",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="role_skills",
            name="role",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="role_skills",
            name="role_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="role_skills",
            name="skill",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="roles",
            name="role",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="roles",
            name="role_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="roles",
            name="salary",
            field=models.IntegerField(default=0),
        ),
    ]
